### ISSUE TITLE
Question: Webhook validation

### ISSUE THREAD

**Issue by dcworldwide** [nozzlegear/Shopify-Prime#10]
Hi, just wondering if the following express middleware will break webhook validation? My webhook validation is failing. Thanks
```

        this.app.use(bodyParser.json())
        this.app.use(bodyParser.urlencoded({ extended: true }))

```

**Comment by dcworldwide** [comment]
I've answered my own question. Yes it does. To get the raw body, i've done the following:

```
// parse application/json. Saving the raw body for webhook validation 
        this.app.use(bodyParser.json({
            verify: function (req: Request, res, buf, encoding) {
                req.rawBody = buf.toString(encoding);
            }
        }))
```

That's for every request...i'm not sure if the overhead of this is significant though....

**Comment by nozzlegear** [comment]
Glad you got it! That's exactly what I do now in my own Express apps after the parser middleware removed the `rawBody` prop from requests.
