### ISSUE TITLE
Better tests!

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/Shopify-Prime#12]
The tests for Shopify Prime are super goofy. I wanted to be able to test the compiled type definitions for the library, so I had to have a project that installed Shopify Prime and used those type definitions, instead of adding a simple test folder which would have ended up using the source types instead. In the end I had a project within a project, which then npm-installed the source project and did some silly things to subvert the yarn cache.

I'm not 100% on a better solution right now, but an idea off the top of my head would be to at least break the test project out into its own repo, or maybe create a special TravisCI test project that only runs tests when we want to release a new version of the lib. 

🤷

**Comment by dcworldwide** [comment]
I've noticed that you stripped the test npm script and removed the test docs from readme.

How do I run the tests in the present state?

**Comment by nozzlegear** [comment]
I'm not able to get to my machine tonight to check, but I believe you need to cd into the tests folder and do `npm run restore`, then `npm run test`. Take a look at the test scripts in the tests/package.json folder though, I believe I set a script for each test subject rather than running them all every time I needed to test something.

I'm going to refactor the whole test process this weekend if I get the chance, because it's super convoluted as is.

**Comment by nozzlegear** [comment]
Woops, that restore command should be `npm run refresh`.

**Comment by dcworldwide** [comment]
Thanks will try :)
