### ISSUE TITLE
Support price rules api

### ISSUE THREAD

**Issue by dcworldwide** [nozzlegear/Shopify-Prime#13]
Are there plans to support the price rules api in the near term? Would love to start experimenting with it.

**Comment by dcworldwide** [comment]
I'm working on this today actually, if you'll accept a PR.

**Comment by nozzlegear** [comment]
I'd be happy to accept a pull request! I don't think I've heard of this API, I wonder if it's a newish one.

**Comment by nozzlegear** [comment]
Added in #14. Thanks!
