### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by xeno** [nozzlegear/Shopify-Prime#19]
I realize the project hasn't been updated in 4 months, but there's lots of new functionality in the latest code. If the project has been abandoned, can we at least get a new release with the updated code?

**Comment by nozzlegear** [comment]
Hey, sorry I didn't realize I forgot to publish the last release. Will do it today and update here once complete.

**Comment by xeno** [comment]
Awesome, thank you! I was hunting through the code on github wondering why I was getting "Products is not a constructor". 😄

**Comment by nozzlegear** [comment]
Okay, 2.5.0 should now be available on NPM! Sorry they got out of sync. I'm currently looking into different methods for converting [ShopifySharp](https://github.com/nozzlegear/shopifysharp) objects and classes to Shopify Prime (and vice versa) as that package is much further along than this one. So hopefully I'll have some big updates for this lib soonish!
