### ISSUE TITLE
Issue verifying webhook: app/uninstalled

### ISSUE THREAD

**Issue by dcworldwide** [nozzlegear/Shopify-Prime#2]
Hi,

I'm having issues verifying webhooks for the app/uninstalled topic.

Client code:

```
            const hmacHeader = req.header("X-Shopify-Hmac-SHA256")
            const body = req.body

            isAuthenticWebhook(hmacHeader, JSON.stringify(body), StoreRoute.appApiSecretKey).then((isAuthentic: boolean) => {
                if (isAuthentic) {
                    res.status(200)
                } else {
                    return next(new Error("Request authentication failed"))
                }
            }).catch(err => {
                return next(err)
            })
```

Parameters:
- X-Shopify-Hmac-SHA256 header: 0rq/AUU4ba+ErHaHhVzQjZePzlKZLOM
- POST Body (abbreviated): {"id":1428231,"name":"AMTEST",......"force_ssl":true}
- I'm using the correct secret api key for my app. 

isAuthenticWebhook returns a different value then the header I received from Shopify.

Any ideas? Am I passing in the body correctly? Thanks

**Comment by nozzlegear** [comment]
Verifying a webhook expects the exact same body that gets sent to your server, so my guess is that calling `JSON.stringify` on your `body` object is putting out a string that is just slightly different from what Shopify sent to your server. Even a single character out of place will change the computed hash. I'm not sure what server framework you're using (probably Express?), but you'll want to find out how to get the raw body string — before it's parsed into an object — and pass that as the second argument to `isAuthenticWebhook`. 

Let me know if that doesn't work!

**Comment by dcworldwide** [comment]
Thanks @nozzlegear for the suggestion. Yep, expressjs. I'll try the raw body string and report back.

**Comment by dcworldwide** [comment]
I'm yet to re test I parked the Web hook auth because I decided to work around it. Will comment here once I get it working.

**Comment by nozzlegear** [comment]
No problem! I'll reopen and investigate if it doesn't work.
