### ISSUE TITLE
Embedded rate limiting 

### ISSUE THREAD

**Issue by dcworldwide** [nozzlegear/Shopify-Prime#20]
Hey @nozzlegear, I've been receiving shopify 429 time out errors of late. 

What are your thoughts on including a built in rate limited to shopify prime?

**Comment by nozzlegear** [comment]
Hey @dcworldwide, sorry I missed this. I'm not a fan of GitHub's new home page design, I miss when it would list opened issues there. 😞

We've built rate limits into ShopifySharp, but they're opt-in so the default behavior is to throw the error unless you specifically turn on retry policies. I'd be happy to merge a pull request for this if you want to work on it, but I'm not using JS/TS much anymore and won't be able to get it done myself.

(I'm about to open an issue looking for maintainers if you're interested.)

**Comment by dcworldwide** [comment]
All good. Ok I'll look at shopify sharps implementation. I will likely create a PR for this when I have the issue next.

Happy to have maintainer access. I'd like for you to still stay involved too however
