### ISSUE TITLE
Running the build npm script

### ISSUE THREAD

**Issue by jdalrymple** [nozzlegear/Shopify-Prime#21]
Everytime i try and run the build npm script, im recieving the error 

```
auth/index.ts(56,9): error TS2322: Type 'string' is not assignable to type 'WordArray'
``` 
is there a reason why this is happening? I havent modified any of the code yet :(

**Comment by nozzlegear** [comment]
Ha, good question! This is one of the reason's I've started using compile-to-js languages instead of JS or TS -- I can never get the builds to reproduce because something always breaks even while using yarn! I'm looking into it right now and will let you know when I get it figured out.

**Comment by jdalrymple** [comment]
I sort of figured it out! Will post the pr in an hour

**Comment by nozzlegear** [comment]
Great! I was able to get it to build for me without any errors, so I'm not sure what the problem may be.

**Comment by jdalrymple** [comment]
Weird 😯 what helped me was by adding any casting on the hash variable. Is it possible we are using different versions of the dependencies ?

**Comment by nozzlegear** [comment]
Well that wouldn't be impossible, I've had NPM build scripts that would build just fine on Windows and then fail on unix/mac, and vice versa. Are you on a mac or Linux machine?

**Comment by nozzlegear** [comment]
Another thought, did you use yarn to install the dependencies, or npm?

**Comment by jdalrymple** [comment]
Lol npm, maybe that's why

**Comment by nozzlegear** [comment]
That might do it! If you use yarn it should install the exact dependencies and then hopefully the build will work.

**Comment by jdalrymple** [comment]
Should I remove the casting then?

**Comment by nozzlegear** [comment]
If it builds once you're using yarn then I think so, I'd like to keep it the way it is as long as there's no build errors.

**Comment by jdalrymple** [comment]
It did thank you!! I removed it from my PR as well
