### ISSUE TITLE
Question: How to use Authscope type?

### ISSUE THREAD

**Issue by dcworldwide** [nozzlegear/Shopify-Prime#3]
Hi, TSC is complaining about the use of auth scope function params.

```
            buildAuthorizationUrl(scope, shopUrl, appApikey, redirectUrl).then((url: string) => {
                res.redirect(url)
            }).catch(err => {
                return next(err)
            })
```

I've tried setting scope to:
- ["read_orders", "read_products"]
- AuthScope.read_orders
- "read_orders"

None of them work :( 

TSC is pretty pedantic...

**Comment by dcworldwide** [comment]
Ok, noticed your tests used `"preserveConstEnums": true`

Learning a lot from your code, thanks 👍

**Comment by nozzlegear** [comment]
Glad to hear you got it worked out! I didn't realize that `preserveConstEnums` was necessary myself, it's just boilerplate that I always have in my own TS projects.

**Comment by dcworldwide** [comment]
Yep, Typescript. The struggle has been real :scream:
