### ISSUE TITLE
Add a helper function for making requests with a leaky bucket policy

### ISSUE THREAD

**Issue by nozzlegear** [nozzlegear/Shopify-Prime#31]
I've typically had a hard time hitting the API rate limit in C# where, just by virtue of the async/await there, my requests only send one at a time in a foreach loop. But my JS apps make liberal use of `Promise.all` to group up all my requests at once, and it's easy to get into a situation where the app immediately slams into the rate limit wall and fails because the requests are all racing each other. It would be great to add a leaky bucket helper function to Shopify Prime to help mitigate the rate limit.

Prior work: 

- https://github.com/nozzlegear/ShopifySharp/blob/master/ShopifySharp/Infrastructure/Policies/SmartRetryExecutionPolicy.cs
- https://github.com/lpinca/stopcock
- https://github.com/salsita/dripping-bucket

**Comment by kcw2099** [comment]
How about use bluebird Promise.map with concurrency option to limit number of requests:
http://bluebirdjs.com/docs/api/promise.map.html

Retry using back-off with an initial random ms:
https://blog.michaelstrasser.com/2017/11/retrying-backend-service-calls-with-backoff/

**Comment by nozzlegear** [comment]
Great suggestion! In the C# version of this lib we have two different retry policies, a "dumb" retry which just naively limits requests and retries after failure, and a "smart" retry which looks at total number of requests being sent to one store plus the response header indicating how many requests can be done. I like the bluebird solution for the "dumb" retry policy and will implement it.
