### ISSUE TITLE
Generated code obscures error stack trace

### ISSUE THREAD

**Issue by episage** [nozzlegear/Shopify-Prime#33]
Hi,

```
Error: [Shopify Prime] 401 Unauthorized.  🍎     at Assets.<anonymous> (/app/node_modules/shopify-prime/dist/infrastructure/base_service.js:78:23) 🍎     at Generator.next (<anonymous>) 🍎     at fulfilled (/app/node_modules/shopify-prime/dist/infrastructure/base_service.js:4:58) 🍎     at process._tickCallback (internal/process/next_tick.js:68:7)
```

Such error is thrown from Shopify-Prime library but for some reason it doesn't print full stack trace pointing to the originating line of code from my code. 
I guess that it is obscured because of TS->JS compilation and in particular transpilation of `async` methods to `process._tickCallback` shims.

Do you know any workaround for this so there is no need to wrap-up the while library in own error rethrows?

**Comment by nozzlegear** [comment]
Hey! I think this is usually just the product of async code in Node, stack traces are typically obscured whenever async functions are involved. I'm not sure but I think later versions of Node (10+ maybe?) make this less confusing and obfuscated. (Feel free if to correct me if I'm wrong, I'm not up-to-date on the latest async information.)
