### ISSUE TITLE
Script bin invocations error

### ISSUE THREAD

**Issue by vinhch** [nozzlegear/Shopify-Prime#9]
In package.json using `node ./node_modules/.bin/tsc -p`, but from what I have researched, it's unnecessary to call like that.
It [breaks on windows](https://github.com/isaacs/rimraf/issues/107), because this script is a shell script, not a node script.  Npm already puts `./node_modules/.bin` in the `PATH` environment variable when running scripts, writes a *.cmd file for use with cmd, and a shell script for use with *nix terminal. So just call `tsc -p`, that is enough.

**Comment by nozzlegear** [comment]
Thanks! I usually use the WSL when working on my node projects, wasn't aware that this was causing problems for Windows.

**Comment by nozzlegear** [comment]
I've got the fix published in version 2.3.1.
